config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  get 'users/new'

  get 'users/show'

  get 'users/create'

  get 'users/update'

  get 'users/edit'

  get 'users/destroy'

  get 'welcome/index'

  root 'welcome#index'

  resources :users

end

app/models/message.rb
#encoding: utf-8

class Message < ActiveRecord::Base

  validates :title, presence: true
  validates :terms_of_service, acceptance: { accept: 'yes' }
  validates :title, format: { with: /\A[a-zA-Z]+\z/,
                                    message: "Допустипы только буквы" }
  validates :title, length: { in: 7..30 }
  validates :comment, length: { maximum: 500 }
  belongs_to :user

end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
end

app/models/user.rb
#encoding: utf-8

class User < ActiveRecord::Base

  has_many :messages
  validates_associated :messages
  validates :email, confirmation: true
  # validates :email_confirmation, presence: true
  validates :age, numericality: { only_integer: true, message: "Только число"}
  validates :email, uniqueness: {message: "Такой email уже есть"}
  validates :name, uniqueness: { case_sensitive: false, message: 'Уникальное имя' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
#encoding: utf-8

class UsersController < ApplicationController

  def index

  end

  def new
    @user = User.new
    # if params[:user]
    #   @user.name = params[:name]
    #   @user.age = params[:age]
    #   @user.email = params[:email]
    #       end

  end

  def show
  end

  def create
    # @users = User.create params[:user]
    @user = User.new
    @user.name = params[:user][:name]
    @user.age = params[:user][:age]
    @user.email = params[:user][:email]
    # @user.save
    if  @user.save
       redirect_to "/users"
    else
      render "new"
    end
 end

  def update
  end

  def edit
  end

  def destroy
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mytest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/destroy.html.erb
<h1>User#destroy</h1>
<p>Find me in app/views/user/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>User#edit</h1>
<p>Find me in app/views/user/edit.html.erb</p>

app/views/users/index.html.haml
%h1 Список пользователей

= link_to 'создать нового пользователя', users_new_path

app/views/users/new.html.haml
#encoding: utf-8

%h1.field_with_errors Новый пользователь
= simple_form_for @user do |f|
  = f.input :name, label: 'Введите имя'
  = f.input :age, collection: 18..60, prompt: "Select your age"
  = f.input :email, placeholder: 'user@domain.com'
  -#= f.input :email_confirmation
  = f.button :submit, "Сохранить", class: "btn btn-info"

app/views/users/show.html.erb
<h1>User#show</h1>
<p>Find me in app/views/user/show.html.erb</p>

app/views/users/update.html.erb
<h1>User#update</h1>
<p>Find me in app/views/user/update.html.erb</p>

app/views/welcome/index.html.haml
%h1 Добро пожаловать!

= link_to 'Перейти к списку пользователей', users_path